# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PPt6aW9gT9wCKzJC3irQUvETVm_Ii6Vx
"""

#PUNTO 1

donacion = int(input('Ingrese la donacion '))

print(f'El valor para Telecomunicaciones es: {donacion*0.1}')
print(f'El valor para Sistemas es: {donacion*0.25}')
print(f'El valor para Administración es: {donacion*0.35}')
print(f'El valor para Contabilidad es: {donacion*0.3}')