# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PPt6aW9gT9wCKzJC3irQUvETVm_Ii6Vx
"""

#PUNTO 3

base = int(input('Ingrese el salario base: '))
valorVenta = int(input('Ingrese el valor de una venta: '))
ventas = int(input('Ingrese las ventas totales del mes: '))

comision = (valorVenta * ventas)*0.15

print(f'El valor ganado por la comision es: {comision}')
print(f'El valor total ganado del vendedor es: {comision + base}')