# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10-C1bubfOTl2aMZJHWWjpJ9WM1Er_kW7
"""

#PUNTO 4

taller1 = int(input('Ingrese el puntaje del taller1: '))
taller2 = int(input('Ingrese el puntaje del taller2: '))
taller3 = int(input('Ingrese el puntaje del taller3: '))
examenClass = int(input('Ingrese el puntaje del examen en clase: '))
finalProject = int(input('Ingrese el puntaje del proyecto final: '))

talleres = ((taller1 + taller2 + taller3)/3)*0.5
print(f'La nota final es : {talleres + (examenClass * 0.3) + (finalProject * 0.2)}')