# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10-C1bubfOTl2aMZJHWWjpJ9WM1Er_kW7
"""

#PUNTO 5

redes = int(input('Ingrese los alumnos de redes: '))
contabilidad = int(input('Ingrese los alumnos de contabilidad: '))
design = int(input('Ingrese los alumnos de design: '))

suma = redes + contabilidad + design
print(f'El porcentaje de alumnos de redes: {(redes * 100) / suma}%')
print(f'El porcentaje de alumnos de contabilidad: {(contabilidad * 100) / suma}%')
print(f'El porcentaje de alumnos de design: {(design * 100) / suma}%')