# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PPt6aW9gT9wCKzJC3irQUvETVm_Ii6Vx
"""

#PUNTO 2

person1 = int(input('Ingrese dinero persona 1: '))
person2 = int(input('Ingrese dinero persona 2: '))
person3 = int(input('Ingrese dinero persona 3: '))

suma = person1 + person2 + person3
print(f'El porcentaje invertido por la persona 1 es: {(person1 * 100) / suma}%')
print(f'El porcentaje invertido por la persona 2 es: {(person2 * 100) / suma}%')
print(f'El porcentaje invertido por la persona 3 es: {(person3 * 100) / suma}%')